version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-test-auth-be
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db


  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio

  mc:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: /bin/sh
    stdin_open: true
    tty: true


volumes:
  mongo-data:
    driver: local
  minio-data:
    driver: local
  minio-config:
    driver: local
